### ISSUE TITLE
I can't run inference successfully because of lacking of your synthetic data

### ISSUE THREAD

**Issue by Dreamlikec** [lorenlugosch/pretrain_speech_model#15]
May I have your synthetic_data.csv?

**Comment by lorenlugosch** [comment]
Here it is: https://zenodo.org/record/3509828

Instead of this old repo, I suggest using my SpeechBrain recipe for Fluent Speech Commands: https://github.com/speechbrain/speechbrain/tree/develop/recipes/fluent-speech-commands
