### ISSUE TITLE
Running model error

### ISSUE THREAD

**Issue by jim2500** [lorenlugosch/pretrain_speech_model#4]
/home/a/anaconda3/bin/python3.7 /home/a/git/slu_1/end-to-end-SLU/test.py
no seq2seq hyperparameters
Traceback (most recent call last):
  File "/home/a/anaconda3/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/home/a/anaconda3/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/a/anaconda3/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'real_dataset_subset_percentage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a/git/slu_1/end-to-end-SLU/test.py", line 7, in <module>
    config = data.read_config("experiments/no_unfreezing.cfg"); _,_,_=data.get_SLU_datasets(config)
  File "/home/a/git/slu_1/end-to-end-SLU/data.py", line 95, in read_config
    config.real_dataset_subset_percentage=float(parser.get("training", "real_dataset_subset_percentage"))
  File "/home/a/anaconda3/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'real_dataset_subset_percentage' in section: 'training'

**Comment by lorenlugosch** [comment]
Ah yeah, I changed the format of the config files, so old ones may break. I'll fix this shortly.

**Comment by jim2500** [comment]
ok，thanks

**Comment by lorenlugosch** [comment]
Sorry for the delay. I've uploaded a fixed version of that config file. Let me know if it still doesn't work!

If anyone else gets this error, that means you just have an old config file, so replace this line:
`dataset_subset_percentage=1`
with these lines:
```
real_dataset_subset_percentage=1.0
synthetic_dataset_subset_percentage=1.0
real_speaker_subset_percentage=1.0
synthetic_speaker_subset_percentage=0.0

```

**Comment by jim2500** [comment]
Thank you very much. But there is still a problem. I don't know if my data set is not downloaded completely.
See the appendix for detailed errors.






At 2019-11-20 04:05:06, "lorenlugosch" <notifications@github.com> wrote:


Sorry for the delay. I've uploaded a fixed version of that config file. Let me know if it still doesn't work!

If anyone else gets this error, that means you just have an old config file, so replace this line:
dataset_subset_percentage=1
with these lines:

real_dataset_subset_percentage=1.0
synthetic_dataset_subset_percentage=1.0
real_speaker_subset_percentage=1.0
synthetic_speaker_subset_percentage=0.0

**Comment by lorenlugosch** [comment]
The problem is probably that you haven't downloaded the synthetic subset of the dataset. You can find it here: https://zenodo.org/record/3509828

**Comment by jim2500** [comment]
I ran the code but still didn't get the results I wanted.

I am a beginner.I don't understand some of these codes.
Thank you so much for your teaching.

**Comment by lorenlugosch** [comment]
Can you paste the bad results you're getting here? Is it an error, or just low accuracy?

**Comment by jim2500** [comment]
I run the test.py file (Figure 1).
Operating results (Figure 2).
No errors, but "no seq2seq hyperparameters" is output.
There should be an exception here (Figure 3), but I don't know where the exception occurred and how to modify it.

**Comment by lorenlugosch** [comment]
I don't see any figures here. Can you copy-paste the output?

**Comment by jim2500** [comment]
Can you receive my attachments? There were three pictures in the attachment in the previous message.

Output: no seq2seq hyperparameters

**Comment by lorenlugosch** [comment]
Pictures don't show up here.

Is "`Output: no seq2seq hyperparameters`" the only output? There's no "`epoch 1: loss, accuracy, etc.`"?

**Comment by jim2500** [comment]
only output“no seq2seq hyperparameters”

At 2019-11-27 23:25:10, "lorenlugosch" <notifications@github.com> wrote:


Pictures don't show up here.

Is "Output: no seq2seq hyperparameters" the only output? There's no "epoch 1: loss, accuracy, etc."?

**Comment by jim2500** [comment]
I run the test.py file:



Output:
No errors, but "no seq2seq hyperparameters" is output.


There should be an exception here , but I don't know where the exception occurred and how to modify it.

**Comment by lorenlugosch** [comment]
Can you print the content of your config file?

**Comment by jim2500** [comment]
no_unfreezing.cfg:
[experiment]
seed=1234
folder=experiments/no_unfreezing

[phoneme_module]
use_sincnet=True
fs=16000

cnn_N_filt=80,60,60
cnn_len_filt=401,5,5
cnn_stride=80,1,1
cnn_max_pool_len=2,1,1
cnn_use_laynorm_inp=True
cnn_use_batchnorm_inp=False
cnn_use_laynorm=True,True,True
cnn_use_batchnorm=False,False,False
cnn_act=leaky_relu,leaky_relu,leaky_relu
cnn_drop=0.0,0.0,0.0

phone_rnn_num_hidden=128,128
phone_downsample_len=2,2
phone_downsample_type=avg,avg
phone_rnn_drop=0.5,0.5
phone_rnn_bidirectional=True

[word_module]
word_rnn_num_hidden=128,128
word_downsample_len=2,2
word_downsample_type=avg,avg
word_rnn_drop=0.5,0.5
word_rnn_bidirectional=True
vocabulary_size=10000

[intent_module]
intent_rnn_num_hidden=128
intent_downsample_len=1
intent_downsample_type=none
intent_rnn_drop=0.5
intent_rnn_bidirectional=True

[pretraining]
asr_path=/scratch/lugosch/librispeech
pretraining_type=2
; 0 - no pre-training, 1 - phoneme loss, 2 - word loss + phoneme loss
pretraining_lr=0.001
pretraining_batch_size=64
pretraining_num_epochs=10
pretraining_length_mean=2.25
pretraining_length_var=1

[training]
slu_path=/home/a/git/ch_commands_datasetd
unfreezing_type=0
; 0 - no unfreezing, 1 - unfreeze word layers, 2 - unfreeze word layers and phoneme layers
training_lr=0.001
training_batch_size=64
training_num_epochs=20
real_dataset_subset_percentage=1.0
synthetic_dataset_subset_percentage=1.0
real_speaker_subset_percentage=1.0
synthetic_speaker_subset_percentage=0.0
train_wording_path=None
; path to .txt file containing phrases to be included during training; if None, uses all phrases
test_wording_path=None

**Comment by jim2500** [comment]
Assertion error:Torch not compiled with CUDA enabled

My machine is cpu only...how can i fix this error?
