### ISSUE TITLE
what's the format of train_data_seq2seq.csv?

### ISSUE THREAD

**Issue by whocares333** [lorenlugosch/pretrain_speech_model#5]
When training under the mode "seq2seq",  the file "xx_data_seq2seq.csv" is needed. But this file is not included in the downloaded dataset. So what's the format of  "xx_data_seq2seq.csv"？

With the format, I can new this file by myself.

**Comment by lorenlugosch** [comment]
Hey, you can find examples of the `_data_seq2seq.csv` files here: https://zenodo.org/record/3509828
(Basically you just list all the slots/values as a single string.)
