### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by xinkez** [lorenlugosch/pretrain_speech_model#6]
Hi, I performed the inference codes, but I got different result. I got different result when I ran the codes every time. Thank you in advance.

**Comment by lorenlugosch** [comment]
Hey, can you clarify what you mean by "different result"? What command did you run and what was the output?

**Comment by xinkez** [comment]
Hi, I used your codes:
[
import data
import models
import soundfile as sf
import torch

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
config = data.read_config("experiments/no_unfreezing.cfg"); _,_,_=data.get_SLU_datasets(config)
model = models.Model(config).eval()
model.load_state_dict(torch.load("experiments/no_unfreezing/training/model_state.pth", map_location=device)) # load trained model

signal, _ = sf.read("test.wav")
signal = torch.tensor(signal, device=device).float().unsqueeze(0)

model.decode_intents(signal)
].

As you mentioned, it should output {"activate", "lights", "kitchen"}. However, I got {"bring", "German", "kitchen"} or anything else.

**Comment by lorenlugosch** [comment]
It looks like the version of the model in `experiments/no_unfreezing/training/model_state.pth` is not up to date, that might have been the problem. Try pulling and running the code again?
