### ISSUE TITLE
Where is the librispeech and the synthesized data?

### ISSUE THREAD

**Issue by picheny-nyu** [lorenlugosch/pretrain_speech_model#7]
I think to run many of these experiments we need to know where the pre-trained librispeech model is, no? I don't obviously see it, can you help?

Also where is the synthesized data you used?

Thanks
Michael

**Comment by lorenlugosch** [comment]
For anyone else reading this:

- Pre-trained LibriSpeech models can be found in any of the "pretraining" experiment folders in this repo (e.g., "https://github.com/lorenlugosch/end-to-end-SLU/tree/master/experiments/unfreeze_word_layers/pretraining"). If you run the training command in the Readme, it will use this pre-trained model if specified in the .cfg file.
- Synthesized data can be found at the Zenodo link from [our ICASSP paper](https://arxiv.org/abs/1910.09463): https://zenodo.org/record/3509828
